name: Test Pipeline

on:
  push:
    branches:
      - main
      - master
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print tree
        run: ls -R
